version: '3.1'
services:
  resapp:
    image: rafale/resapp
    restart: always
    volumes:
      - ./db:/app/db
    labels:
      - traefik.http.routers.website.rule=Host(`ateliersr3.christobrary.net`)
      - traefik.http.services.my-service.loadbalancer.server.port=3580
